services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth
    ports:
      - 5432:5432
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
