// Package public GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package public

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Validate credentials, return access and refresh tokens.",
                "tags": [
                    "auth"
                ],
                "summary": "Generate auth tokens.",
                "operationId": "Login",
                "parameters": [
                    {
                        "description": "user credentials",
                        "name": "credentials",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/http.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/validate": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "Validate tokens and refresh tokens if refresh token is valid",
                "tags": [
                    "auth"
                ],
                "summary": "Validate tokens",
                "operationId": "Validate",
                "parameters": [
                    {
                        "description": "user tokens",
                        "name": "tokens",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/http.TokenPair"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/http.TokenPair"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.TokenPair": {
            "type": "object",
            "properties": {
                "authToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "http.User": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Auth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/auth/v1",
	Schemes:          []string{"http"},
	Title:            "Example for lecture",
	Description:      "Signed token protects our admin endpoints",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
